CXX = g++
CXXFLAGS = -g -Wall --pedantic -fno-elide-constructors -std=c++20 -O3
MEASUREMENT_PATH = -I ~/Desktop/codes/measurements/include

compile: main.cpp
	$(CXX) $(CXXFLAGS) $(MEASUREMENT_PATH) -o $@ $<